name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
          description: Provide the Ingress URL
          required: true
          type: string
    outputs:
      ingress-url:
        description: Application Ingress URL
        value: ${{ jobs.integration-test.outputs.ingress-url }}
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get ingress URL
        id: ingress
        run: |
         URL=$(kubectl get ingress solar-system \
         -o jsonpath='{.spec.rules[0].host}')
         echo "url=$URL" >> $GITHUB_OUTPUT
      - name: Debug URL
        run: |
         echo "URL=${{ inputs.ingress-url }}"
      - env:
          URL: ${{ inputs.ingress-url }}
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live